### ISSUE TITLE
orthofinder results directory

### ISSUE THREAD

**Issue by r-mashoodh** [Eco-Flow/comparete#9]
currently orthofinder results end up in a work directory under work/d/i/r/s/My_result/Results_$date/

think we need to move this to results?

**Comment by chriswyatt1** [comment]
Hey @r-mashoodh , I tried the pipeline with (takes 2 mins to run):

`nextflow run main.nf -profile docker,test_bacteria -resume --orthofinder`

And it worked as expected with the results/orthofinder folder

<img width="286" alt="image" src="https://github.com/user-attachments/assets/45ffe8ce-bdbd-479c-80a2-a71a7101b2bc">


Maybe your run didn't finish? Or died? Maybe check the pipeline execution log in the pipeline_info results folder

**Comment by chriswyatt1** [comment]
I have made it so that all the orthofinder output will all be sent to publish dir. Not just specific files:

[25f08eb](https://github.com/Eco-Flow/comparete/commit/25f08eb7515e4e5ddd956e7b1e03fba6d3a969b0)
